// src/lib/components/History.svelte
<script lang="ts">
	import { Input } from '#lib/components/ui/input/index.js';
	import { Button } from '#lib/components/ui/button/index.js';
	import PriceChart from './PriceChart.svelte';
	import * as Tabs from '#lib/components/ui/tabs/index.js';
	import { Badge } from '#lib/components/ui/badge/index.js';
	import { Search, ArrowLeft, ChevronRight } from '@lucide/svelte';
	import { productHistory, productPrices, matchLabel, type Receipt } from '#lib/domain/insights.js';
	import { formatMoney } from '#lib/domain/receipt.js';
	import ReceiptCard from './ReceiptCard.svelte';
	let { receipts, onopen }: { receipts: Receipt[]; onopen: (receipt: Receipt) => void } = $props();
	let search = $state('');
	let tab = $state<'receipts' | 'products'>('receipts');
	let selectedKey = $state<string | null>(null);
	const filtered = $derived(
		receipts.filter((receipt) =>
			[
				receipt.data?.store,
				receipt.data?.purchaseDate,
				...(receipt.data?.lines.flatMap((line) => [line.name, line.originalText, ...line.tags]) ??
					[])
			]
				.join(' ')
				.toLocaleLowerCase('nb-NO')
				.includes(search.toLocaleLowerCase('nb-NO'))
		)
	);
	const products = $derived(
		productHistory(receipts).filter((product) =>
			product.name.toLocaleLowerCase('nb-NO').includes(search.toLocaleLowerCase('nb-NO'))
		)
	);
	const selected = $derived(products.find((product) => product.key === selectedKey));
	const prices = $derived(selected ? productPrices(selected.contributions) : null);
</script>

<div class="page-heading">
	<div class="section-eyebrow">DET DERE HAR HANDLET</div>
	<h1>Historikk</h1>
</div>
<label class="search-field"
	><Search size={19} /><Input
		aria-label="Søk i historikk"
		placeholder="Søk etter butikk, vare eller etikett"
		bind:value={search}
	/></label
>
<div class="section-header">
	<Tabs.Root bind:value={tab}
		><Tabs.List
			><Tabs.Trigger value="receipts" onclick={() => (selectedKey = null)}
				>Kvitteringer</Tabs.Trigger
			><Tabs.Trigger value="products">Varer</Tabs.Trigger></Tabs.List
		></Tabs.Root
	>
	<span class="muted small">{tab === 'receipts' ? filtered.length : products.length} treff</span>
</div>
{#if selected && tab === 'products'}
	<section class="panel">
		<Button variant="ghost" class="text-button" onclick={() => (selectedKey = null)}
			><ArrowLeft size={16} />Alle varer</Button
		>
		<h2>{selected.name}</h2>
		<p>{selected.purchases.size} kjøp · {formatMoney(selected.amountOre)} til sammen</p>
		<p class="footnote">
			{selected.linked
				? 'Prisene gjelder samme koblede produkt fra denne butikken.'
				: 'Varen er ikke bekreftet som en match. Den vises separat.'}
		</p>
		{#if prices && prices.observations.length}
			<h3>Beløp per kjøp</h3>
			<p class="footnote">
				Etter varerabatter. Typisk = median. Kvitteringsrabatter er ikke fordelt.
			</p>
			<div class="grid grid-cols-3 gap-3 my-5">
				{#each [{ label: 'Siste', value: prices.latest }, { label: 'Typisk', value: prices.typical }, { label: 'Laveste', value: prices.lowest }] as metric (metric.label)}<div
					>
						<p class="text-xs text-muted-foreground">{metric.label}</p>
						<strong class="text-base tabular-nums">{formatMoney(metric.value)}</strong>
					</div>{/each}
			</div>
			<PriceChart {prices} {onopen} />
			{#if prices.omitted}<p class="footnote">
					{prices.omitted} kjøp uten dato eller positivt beløp er utelatt fra diagrammet.
				</p>{/if}
		{/if}

		{#each [...selected.contributions].sort( (a, b) => (a.receipt.data?.purchaseDate ?? '').localeCompare(b.receipt.data?.purchaseDate ?? '') ) as contribution, index (index)}<Button
				variant="ghost"
				class="contribution-row"
				onclick={() => onopen(contribution.receipt)}
				><span
					><strong>{contribution.receipt.data?.purchaseDate ?? 'Dato ukjent'}</strong
					>{#if contribution.line}<Badge variant="secondary">{matchLabel(contribution.line)}</Badge
						>{/if}<small
						>{contribution.receipt.data?.store} · {contribution.receipt.status === 'reviewed'
							? 'Kontrollert'
							: 'Foreløpig'}</small
					></span
				><strong>{formatMoney(contribution.amountOre)}</strong><ChevronRight size={16} /></Button
			>{/each}
	</section>
{:else if tab === 'products'}
	<div class="panel">
		{#each products as product (product.key)}<Button
				variant="ghost"
				class="contribution-row"
				onclick={() => (selectedKey = product.key)}
				><span
					><strong>{product.name || 'Ukjent vare'}</strong><small
						>{product.purchases.size} kjøp · {product.linked
							? 'Koblet produkt'
							: 'Enkeltvare, ikke slått sammen'}</small
					></span
				><strong>{formatMoney(product.amountOre)}</strong><ChevronRight size={16} /></Button
			>{:else}<div class="empty-state">
				<Search size={28} />
				<h3>Ingen varer funnet</h3>
				<p>Prøv et annet søk, eller legg til en kvittering.</p>
			</div>{/each}
	</div>
{:else}<div class="receipt-list">
		{#each filtered as receipt (receipt._id)}<ReceiptCard {receipt} {onopen} />{:else}<div
				class="empty-state"
			>
				<Search size={28} />
				<h3>Ingen kvitteringer funnet</h3>
			</div>{/each}
	</div>{/if}

// src/app/(tabs)/history/index.tsx
import { CalendarDate, CalendarMonth } from "@/lib/domain/calendar";
import { Ore } from "@/lib/domain/ore";
import {
  contributionKey,
  matchLabel,
  productHistory,
  productPrices,
} from "@/lib/domain/insights";
import { ReceiptContextMenu } from "@/features/receipt-context-menu";
import { router, Stack } from "expo-router";
import {
  useCompleteReceipts,
  useReceiptHistory,
} from "@/features/receipt-queries";
import { useDebouncedSearch } from "@/features/catalog-queries";
import { useState } from "react";
import { Platform, View, useWindowDimensions } from "react-native";
import {
  Amount,
  Button,
  Copy,
  Empty,
  Field,
  List,
  Loading,
  Notice,
  Panel,
  Row,
  Screen,
  SectionTitle,
  Segments,
  SettingsButton,
  Sheet,
} from "@/components/ui";
import { IllustratedEmpty } from "@/components/monument-artwork";
import { openReceipt } from "@/components/receipt-card";
import { SpendingBars } from "@/components/spending-details";
import { OfflineNotice } from "@/features/offline-notice";

export default function History() {
  const { fontScale } = useWindowDimensions();
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<"receipts" | "products">("receipts");
  const [selectedKey, setSelectedKey] = useState<string | null>(null);

  const matches = (value: string) =>
    value
      .toLocaleLowerCase("nb-NO")
      .includes(search.trim().toLocaleLowerCase("nb-NO"));

  const term = useDebouncedSearch(search.trim());
  const history = useReceiptHistory(term, tab === "receipts");

  const { receipts, completeReceipts: completeProducts } = useCompleteReceipts(
    { kind: "allProducts" },
    tab === "products",
  );

  const filtered = history.results;

  const completeReceipts =
    tab === "products" ? completeProducts : history.status === "Exhausted";

  const loadingReceipts =
    tab === "products"
      ? !completeProducts
      : history.status === "LoadingFirstPage";

  const sorted = [...filtered].sort(
    (a, b) =>
      CalendarDate.compare(b.purchaseDate, a.purchaseDate) ||
      b._creationTime - a._creationTime,
  );

  const months = new Map<CalendarMonth | "unknown", typeof sorted>();

  for (const receipt of sorted) {
    const key = receipt.purchaseDate
      ? CalendarDate.month(receipt.purchaseDate)
      : "unknown";

    months.set(key, [...(months.get(key) ?? []), receipt]);
  }

  const monthTitle = (key: CalendarMonth | "unknown") =>
    key === "unknown" ? "Uten dato" : CalendarMonth.title(key);

  const allProducts = productHistory(receipts);
  const products = allProducts.filter((product) => matches(product.name));
  const selected = allProducts.find((product) => product.key === selectedKey);
  const prices = selected ? productPrices(selected.contributions) : null;

  return (
    <Screen
      title={Platform.OS === "ios" ? undefined : "Historikk"}
      settings={Platform.OS !== "ios"}
      insetTop={Platform.OS !== "ios"}
    >
      {Platform.OS === "ios" && (
        <>
          <Stack.SearchBar
            placeholder="Butikk, vare eller etikett"
            onChangeText={(event) => setSearch(event.nativeEvent.text)}
            hideWhenScrolling={false}
          />
          <Stack.Toolbar placement="right">
            <Stack.Toolbar.View hidesSharedBackground>
              <SettingsButton />
            </Stack.Toolbar.View>
          </Stack.Toolbar>
        </>
      )}
      {Platform.OS !== "ios" && (
        <Field
          label="Søk"
          placeholder="Butikk, vare eller etikett"
          value={search}
          onChangeText={setSearch}
          clearButtonMode="while-editing"
          autoCorrect={false}
        />
      )}
      <Segments
        value={tab}
        onChange={setTab}
        options={[
          { value: "receipts", label: `Kvitteringer (${filtered.length})` },
          { value: "products", label: `Varer (${products.length})` },
        ]}
      />
      <OfflineNotice />
      {!completeReceipts && (
        <Notice>
          {tab === "products" || term
            ? "Henter hele resultatet …"
            : "Viser innlastede kvitteringer."}
        </Notice>
      )}
      {loadingReceipts ? (
        <Loading />
      ) : (
        <>
          {tab === "receipts" &&
            [...months.entries()].map(([key, items]) => {
              const total = Ore.sum(
                items.map((receipt) => receipt.spendingOre),
              );

              return (
                <View key={key} style={{ gap: 4 }}>
                  <SectionTitle
                    title={monthTitle(key)}
                    detail={`${items.length} ${items.length === 1 ? "kvittering" : "kvitteringer"} · ${Ore.format(total)}`}
                  />
                  <List>
                    {items.map((receipt) => (
                      <ReceiptContextMenu
                        key={receipt._id}
                        receiptId={receipt._id}
                        store={receipt.store || "Ny kvittering"}
                        amount={Ore.format(receipt.totalOre)}
                        date={CalendarDate.format(receipt.purchaseDate)}
                      >
                        <Row
                          title={receipt.store || "Ny kvittering"}
                          detail={CalendarDate.format(receipt.purchaseDate)}
                          value={Ore.format(receipt.totalOre)}
                          onPress={() =>
                            router.push({
                              pathname: "/receipt/[id]",
                              params: { id: receipt._id },
                            })
                          }
                        />
                      </ReceiptContextMenu>
                    ))}
                  </List>
                </View>
              );
            })}
          {tab === "products" && (
            <List>
              {products.map((product) => (
                <Row
                  key={product.key}
                  title={product.name || "Ukjent vare"}
                  detail={`${product.purchases.size} kjøp · ${product.linked ? "Koblet produkt" : "Enkeltvare"}`}
                  value={Ore.format(product.amountOre)}
                  onPress={() => setSelectedKey(product.key)}
                />
              ))}
            </List>
          )}
          {(tab === "receipts" ? filtered : products).length === 0 &&
            (search.trim() || tab === "products" ? (
              <Empty title="Ingen treff" icon="magnifyingglass" />
            ) : (
              <IllustratedEmpty
                scene="history"
                title="Historikken begynner her"
                message="Lagrede kvitteringer vises her når de er behandlet."
              />
            ))}
        </>
      )}
      {tab === "receipts" && history.status === "CanLoadMore" && !term && (
        <Button
          title="Vis flere kvitteringer"
          variant="secondary"
          onPress={() => history.loadMore(30)}
        />
      )}
      <Sheet
        title={selected?.name || "Varehistorikk"}
        visible={!!selected}
        onClose={() => setSelectedKey(null)}
      >
        {selected && prices && (
          <>
            <Amount detail={`${selected.purchases.size} kjøp`}>
              {Ore.format(selected.amountOre)}
            </Amount>
            <Panel
              style={{
                flexDirection: fontScale > 1.3 ? "column" : "row",
                gap: 16,
              }}
            >
              {[
                { label: "Siste", amount: prices.latest },
                { label: "Typisk", amount: prices.typical },
                { label: "Laveste", amount: prices.lowest },
              ].map((metric) => (
                <View key={metric.label} style={{ flex: 1, gap: 2 }}>
                  <Copy muted role="caption" weight="600">
                    {metric.label}
                  </Copy>
                  <Copy weight="700" role="cardTitle">
                    {Ore.format(metric.amount)}
                  </Copy>
                </View>
              ))}
            </Panel>
            <SpendingBars
              rows={prices.observations.map((observation, index) => ({
                id: String(index),
                name: CalendarDate.format(observation.date),
                amountOre: observation.ore,
                contributions: [observation.contribution],
              }))}
              onSelect={(row) => {
                const [contribution] = row.contributions;
                setSelectedKey(null);

                if (contribution) openReceipt(contribution.receipt);
              }}
            />
            {prices.omitted > 0 && (
              <Notice>
                {prices.omitted} kjøp uten dato eller positivt beløp er utelatt
                fra diagrammet.
              </Notice>
            )}
            <List>
              {selected.contributions.map((contribution) => (
                <Row
                  key={contributionKey(contribution)}
                  title={CalendarDate.format(
                    contribution.receipt.data?.purchaseDate,
                  )}
                  detail={`${contribution.receipt.data?.store} · ${contribution.line ? matchLabel(contribution.line) : ""}`}
                  value={Ore.format(contribution.amountOre)}
                  onPress={() => {
                    setSelectedKey(null);
                    openReceipt(contribution.receipt);
                  }}
                />
              ))}
            </List>
          </>
        )}
      </Sheet>
    </Screen>
  );
}
