// src/lib/components/Spending.svelte
<script lang="ts">
	import * as Card from '#lib/components/ui/card/index.js';
	import { Button } from '#lib/components/ui/button/index.js';
	import * as Sheet from '#lib/components/ui/sheet/index.js';
	import * as Tabs from '#lib/components/ui/tabs/index.js';
	import SpendingChart from './SpendingChart.svelte';
	import SpendingCalendar from './SpendingCalendar.svelte';
	import {
		ChevronLeft,
		ChevronRight,
		ArrowUpRight,
		ArrowDownRight,
		ArrowLeft,
		ShoppingBasket,
		ReceiptText
	} from '@lucide/svelte';
	import {
		comparisonInsights,
		receiptCoverage,
		type Receipt,
		type SpendingGroup,
		type Contribution
	} from '#lib/domain/insights.js';
	import { formatMoney, osloDate } from '#lib/domain/receipt.js';
	import { categoryById } from '#lib/domain/categories.js';
	let { receipts, onopen }: { receipts: Receipt[]; onopen: (receipt: Receipt) => void } = $props();
	let month = $state(osloDate().slice(0, 7));
	let reviewedOnly = $state(false);
	let breakdown = $state<'category' | 'store' | 'type'>('category');
	let selected = $state<SpendingGroup | null>(null);
	let group = $state<string | null>(null);
	const comparison = $derived(comparisonInsights(receipts, month, reviewedOnly));
	const totals = $derived(comparison.current);
	const previous = $derived(comparison.previous);
	const coverage = $derived(receiptCoverage(receipts));
	const proteins = $derived(
		['poultry', 'pork', 'lamb', 'beef', 'fish'].map(
			(id) =>
				totals.categories.find((c) => c.id === `meat-fish.${id}`) ?? {
					id: `meat-fish.${id}`,
					name: categoryById.get(`meat-fish.${id}`)?.name ?? id,
					amountOre: 0,
					contributions: []
				}
		)
	);
	let sheetOpen = $state(false);
	const change = $derived(
		previous.products === 0
			? null
			: Math.round(((totals.products - previous.products) / Math.abs(previous.products)) * 100)
	);
	const rows = $derived(
		breakdown === 'type'
			? totals.purchaseTypes
			: breakdown === 'store'
				? totals.stores
				: group
					? totals.categories.filter(
							(c) =>
								categoryById.get(c.id)?.group === group ||
								(group === 'fallback' && c.id === 'unallocated')
						)
					: totals.groups
	);
	const monthLabel = $derived(
		new Intl.DateTimeFormat('nb-NO', {
			month: 'long',
			year: 'numeric',
			timeZone: 'Europe/Oslo'
		}).format(new Date(month + '-01T12:00:00Z'))
	);
	function periodLabel(end: string) {
		return `1.–${new Intl.DateTimeFormat('nb-NO', { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'Europe/Oslo' }).format(new Date(end + 'T12:00:00Z'))}`;
	}
	function moveMonth(offset: number) {
		const [year, value] = month.split('-').map(Number);
		month = new Date(Date.UTC(year, value - 1 + offset, 1)).toISOString().slice(0, 7);
		selected = null;
		group = null;
	}
	function selectTotal(name: string, amountOre: number, contributions: Contribution[]) {
		selected = { id: name, name, amountOre, contributions };
		sheetOpen = true;
	}
	const accounting = $derived(
		totals.selected.flatMap((receipt) =>
			receipt.data!.lines.map((line) => ({ receipt, line, amountOre: line.amountOre ?? 0 }))
		)
	);
</script>

<div class="page-heading">
	<div>
		<div class="section-eyebrow">HUSSTANDENS FORBRUK</div>
		<h1>Forbruk</h1>
	</div>
</div>
<div class="month-control">
	<Button
		variant="ghost"
		class="icon-button"
		aria-label="Forrige måned"
		onclick={() => moveMonth(-1)}><ChevronLeft size={19} /></Button
	><strong>{monthLabel}</strong><Button
		variant="ghost"
		class="icon-button"
		aria-label="Neste måned"
		onclick={() => moveMonth(1)}><ChevronRight size={19} /></Button
	>
</div>
<label class="check-label"
	><input type="checkbox" bind:checked={reviewedOnly} /> Bare kontrollerte kvitteringer</label
>
<div class="spending-hero">
	<span>Registrert vareforbruk, uten pant</span><strong>{formatMoney(totals.products)}</strong>
	<div class="comparison">
		{#if change !== null}{#if change > 0}<ArrowUpRight size={16} />{:else}<ArrowDownRight
					size={16}
				/>{/if}{Math.abs(change)} % {change > 0 ? 'mer' : 'mindre'} i sammenligningsperioden{:else}Ingen
			sammenligning for forrige måned{/if}
	</div>
	<p class="text-sm opacity-80">
		{periodLabel(comparison.currentEnd)} mot {periodLabel(comparison.previousEnd)}. {comparison.partial
			? 'Samme del av måneden.'
			: 'Hele måneder.'}
	</p>
	<div class="hero-footer">
		<span>{totals.selected.length} kvitteringer</span><span
			>{totals.provisional ? `${totals.provisional} foreløpige` : 'Alle kontrollert'}</span
		>
	</div>
</div>
<Card.Root class="panel gap-0">
	<div class="section-header">
		<h2>Kjøtt og fisk</h2>
		<span class="muted small">Registrerte kjøp</span>
	</div>
	<SpendingChart
		rows={proteins}
		onselect={(row) => {
			selected = row;
			sheetOpen = true;
		}}
	/>
	<p class="footnote">Råvarer i kjøtt og fisk. Pålegg og ferdigretter har egne kategorier.</p>
</Card.Root>
<SpendingCalendar
	{receipts}
	year={Number(month.slice(0, 4))}
	{reviewedOnly}
	onselect={(day) => {
		selected = day;
		sheetOpen = true;
	}}
/>
{#if coverage.pending.length || coverage.unlinkedCount}<section class="panel">
		<h2>Datagrunnlag</h2>
		<p class="footnote">Status for alle registrerte kvitteringer, uavhengig av måned.</p>
		<Button
			variant="ghost"
			class="contribution-row"
			onclick={() =>
				selectTotal(
					'Kvitteringer til kontroll',
					0,
					coverage.pending.map((receipt) => ({
						receipt,
						line: null,
						amountOre: receipt.data?.totalOre ?? 0
					}))
				)}
			><span>{coverage.pending.length} kvitteringer til kontroll</span><ChevronRight
				size={16}
			/></Button
		>
		<Button
			variant="ghost"
			class="contribution-row"
			onclick={() =>
				selectTotal(
					'Varer uten produktkobling',
					0,
					coverage.unlinked.map((receipt) => ({
						receipt,
						line: null,
						amountOre: receipt.data?.totalOre ?? 0
					}))
				)}
			><span>{coverage.unlinkedCount} varer uten produktkobling</span><ChevronRight
				size={16}
			/></Button
		>
	</section>{/if}
{#if previous.selected.length && comparison.changes.length}<section class="panel">
		<h2>Største endringer</h2>
		<p class="footnote">
			Endring i registrert forbruk mellom periodene. Dette kan skyldes både antall kjøp og priser.
		</p>
		{#each comparison.changes.slice(0, 3) as item (item.id)}<Button
				variant="ghost"
				class="contribution-row"
				onclick={() => selectTotal(item.name, item.current, item.currentContributions)}
				><span
					><strong>{item.name}</strong><small
						>{formatMoney(item.previous)} → {formatMoney(item.current)}</small
					></span
				><strong>{item.difference > 0 ? '+' : ''}{formatMoney(item.difference)}</strong
				><ChevronRight size={16} /></Button
			>{/each}
		<Button
			variant="ghost"
			class="text-button"
			onclick={() =>
				selectTotal(
					'Forrige periode',
					previous.products,
					comparison.changes.flatMap((c) => c.previousContributions)
				)}>Se kjøp i forrige periode</Button
		>
	</section>{/if}
<div class="metric-grid">
	<Button
		variant="ghost"
		class="metric"
		onclick={() =>
			selectTotal(
				'Betalt',
				totals.paid,
				totals.selected.map((receipt) => ({
					receipt,
					line: null,
					amountOre: receipt.data?.totalOre ?? 0
				}))
			)}
		><span>Betalt</span><strong>{formatMoney(totals.paid)}</strong><small
			>Inkludert pant <ChevronRight size={12} /></small
		></Button
	>
	<Button
		variant="ghost"
		class="metric"
		onclick={() =>
			selectTotal(
				'Registrerte rabatter',
				totals.discounts,
				accounting.filter(
					(c) => c.line?.kind === 'item_discount' || c.line?.kind === 'receipt_discount'
				)
			)}
		><span>Registrerte rabatter</span><strong>{formatMoney(totals.discounts)}</strong><small
			>Allerede trukket fra <ChevronRight size={12} /></small
		></Button
	>
	<Button
		variant="ghost"
		class="metric"
		onclick={() =>
			selectTotal(
				'Pant betalt',
				totals.deposits,
				accounting.filter((c) => c.line?.kind === 'deposit')
			)}
		><span>Pant betalt</span><strong>{formatMoney(totals.deposits)}</strong><small
			>Holdes utenfor varer <ChevronRight size={12} /></small
		></Button
	>
	<Button
		variant="ghost"
		class="metric"
		onclick={() =>
			selectTotal(
				'Pant returnert',
				totals.returns,
				accounting.filter((c) => c.line?.kind === 'deposit_return')
			)}
		><span>Pant returnert</span><strong>{formatMoney(totals.returns)}</strong><small
			>Tilbakebetalt <ChevronRight size={12} /></small
		></Button
	>
</div>
{#if totals.unconverted.length}<div class="notice warning">
		<div>
			<strong>{totals.unconverted.length} kvittering(er) har ukjent eller annen valuta</strong>
			<p>Disse er utenfor NOK-summene. Kontroller valutaen på kvitteringen.</p>
			{#each totals.unconverted as receipt (receipt._id)}<Button
					variant="ghost"
					class="text-button"
					onclick={() => onopen(receipt)}
					>{receipt.data?.store ?? 'Ukjent butikk'} · Åpne kvittering</Button
				>{/each}
		</div>
	</div>{/if}
{#if totals.unknownTotals}<p class="notice warning">
		{totals.unknownTotals} kvittering(er) mangler betalt beløp. Summen er ufullstendig.
	</p>{/if}
{#if totals.undated.length}<div class="notice warning">
		<div>
			<strong>{totals.undated.length} kvittering(er) mangler dato</strong>
			<p>Disse er utenfor månedsoversikten.</p>
			{#each totals.undated as receipt (receipt._id)}<Button
					variant="ghost"
					class="text-button"
					onclick={() => onopen(receipt)}
					>{receipt.data?.store ?? 'Ukjent butikk'} · Åpne kvittering</Button
				>{/each}
		</div>
	</div>{/if}
{#if totals.unknownAmounts}<p class="notice warning">
		{totals.unknownAmounts} linje(r) mangler beløp. Vareforbruket er ufullstendig.
	</p>{/if}
{#if totals.suspectedDuplicates.length}<div class="notice warning">
		<div>
			<strong
				>{totals.suspectedDuplicates.length} mulig(e) duplikat(er) er med i foreløpige summer.</strong
			>{#each totals.suspectedDuplicates as receipt (receipt._id)}<Button
					variant="ghost"
					class="text-button"
					onclick={() => onopen(receipt)}>Kontroller {receipt.data?.store ?? 'kvittering'}</Button
				>{/each}
		</div>
	</div>{/if}
{#if totals.discrepancies.length}<div class="notice warning">
		<div>
			<strong
				>Varer og betalt beløp stemmer ikke på {totals.discrepancies.length} kvittering(er).</strong
			>{#each totals.discrepancies as receipt (receipt._id)}<Button
					variant="ghost"
					class="text-button"
					onclick={() => onopen(receipt)}>Kontroller {receipt.data?.store ?? 'kvittering'}</Button
				>{/each}
		</div>
	</div>{/if}
<section class="panel breakdown">
	<div class="section-header">
		<h2>{group ? totals.groups.find((row) => row.id === group)?.name : 'Fordeling'}</h2>
		<Tabs.Root bind:value={breakdown}>
			<Tabs.List
				><Tabs.Trigger value="type" onclick={() => (group = null)}>Varetype</Tabs.Trigger
				><Tabs.Trigger value="category" onclick={() => (group = null)}>Kategori</Tabs.Trigger
				><Tabs.Trigger value="store" onclick={() => (group = null)}>Butikk</Tabs.Trigger></Tabs.List
			>
		</Tabs.Root>
	</div>
	{#if group}<Button variant="ghost" class="text-button" onclick={() => (group = null)}
			><ArrowLeft size={15} />Alle kategorier</Button
		>{/if}
	<SpendingChart
		{rows}
		onselect={(row) => {
			if (breakdown === 'category' && !group) group = row.id;
			else {
				selected = row;
				sheetOpen = true;
			}
		}}
	/>
	{#if !rows.length}<div class="empty-state">
			<ShoppingBasket size={30} />
			<h3>Ingen registrerte kjøp</h3>
			<p>Legg til en kvittering for å se forbruket.</p>
		</div>{/if}
	<p class="footnote">Uavklart forbruk er inkludert. Foreløpige beløp kan endres ved kontroll.</p>
</section>
<Sheet.Root bind:open={sheetOpen}
	><Sheet.Content
		side="bottom"
		class="mx-auto max-h-[85dvh] max-w-2xl overflow-y-auto rounded-t-2xl p-6"
	>
		{#if selected}<Sheet.Header
				><Sheet.Title>{selected.name}</Sheet.Title><Sheet.Description
					>Varer og kvitteringer som inngår i oversikten.</Sheet.Description
				></Sheet.Header
			>
			<section class="contribution-panel">
				{#each selected.contributions as contribution, index (`${contribution.receipt._id}-${index}`)}<Button
						variant="ghost"
						class="contribution-row"
						onclick={() => {
							sheetOpen = false;
							onopen(contribution.receipt);
						}}
						><ReceiptText size={17} /><span
							><strong
								>{contribution.line?.name ??
									contribution.receipt.data?.store ??
									'Kvittering'}</strong
							><small
								>{contribution.receipt.data?.purchaseDate ?? 'Dato ukjent'} · {contribution.receipt
									.status === 'reviewed'
									? 'Kontrollert'
									: 'Foreløpig'}</small
							></span
						><strong
							>{contribution.line?.amountOre === null
								? 'Ukjent beløp'
								: formatMoney(contribution.amountOre)}</strong
						><ChevronRight size={16} /></Button
					>{:else}<p class="muted">Ingen linjer i denne perioden.</p>{/each}
			</section>{/if}</Sheet.Content
	></Sheet.Root
>

// src/app/(tabs)/spending.tsx
import {
  useSpendingReports,
  reportIds,
  type ReportId,
} from "@/features/spending-reports/reports";
import {
  resolveSpendingSelection,
  type SpendingSelection,
  type SpendingDimension,
} from "@/lib/spending-selection";
import { attributeInsights } from "@/lib/domain/attribute-insights";
import { spendingCalendar, monthBefore } from "@/lib/domain/insights";
import { useCompleteReceipts } from "@/features/receipt-queries";
import { useState } from "react";
import { Pressable, View } from "react-native";
import {
  Button,
  Copy,
  Icon,
  IconButton,
  Sheet,
  Empty,
  Loading,
  Notice,
  Panel,
  Row,
  Screen,
  SectionTitle,
  Segments,
  Toggle,
  pressed,
} from "@/components/ui";
import { MonumentArtwork } from "@/components/monument-artwork";
import { SpendingBars, SpendingDetails } from "@/components/spending-details";
import { useHousehold } from "@/features/session";
import {
  comparisonInsights,
  receiptCoverage,
  type SpendingGroup,
} from "@/lib/domain/insights";
import { formatMoney, osloDate } from "@/lib/domain/receipt";
import { categoryById } from "@/lib/domain/categories";
import { receiptNeeds } from "@/components/receipt-card";
import { useTheme } from "@/constants/theme";
import { budgetPace, paceLabel } from "@/lib/domain/budget";
import { monthPriceSignals } from "@/lib/domain/price-signals";
import { catalogInsights } from "@/lib/catalog/insights";
import { router } from "expo-router";
import { StoreSpendingSheet } from "@/features/spending-reports/stores";

export default function Spending() {
  const { online, details } = useHousehold();
  const colors = useTheme();
  const currentMonth = osloDate().slice(0, 7);
  const [month, setMonth] = useState(currentMonth);

  const { receipts, loadingReceipts, completeReceipts } = useCompleteReceipts({
    kind: "period",
    start: `${monthBefore(month)}-01`,
    end: `${month}-31`,
  });

  const [filters, setFilters] = useState(false);
  const [storesOpen, setStoresOpen] = useState(false);
  const [report, setReport] = useState<ReportId | null>(null);
  const [showAllGroups, setShowAllGroups] = useState(false);
  const [reviewedOnly, setReviewedOnly] = useState(false);

  const [breakdown, setBreakdown] = useState<"category" | "store" | "type">(
    "category",
  );

  const [group, setGroup] = useState<string | null>(null);
  const [selection, setSelection] = useState<SpendingSelection | null>(null);
  const periodKey = JSON.stringify([month, reviewedOnly]);

  const undated = useCompleteReceipts(
    { kind: "undated" },
    report === "coverage" || selection?.key === "unlinked",
  );

  const comparison = comparisonInsights(receipts, month, reviewedOnly);
  const totals = comparison.current;
  const coverage = receiptCoverage([...receipts, ...undated.receipts]);
  const catalog = catalogInsights(totals.selected);

  const change = comparison.previous.products
    ? Math.round(
        ((totals.products - comparison.previous.products) /
          Math.abs(comparison.previous.products)) *
          100,
      )
    : null;

  const rows =
    breakdown === "store"
      ? totals.stores
      : breakdown === "type"
        ? totals.purchaseTypes
        : group
          ? totals.categories.filter(
              (category) =>
                categoryById.get(category.id)?.group === group ||
                (group === "fallback" && category.id === "unallocated"),
            )
          : totals.groups;

  const showDetails = (
    value: SpendingGroup,
    dimension: SpendingDimension = "category",
  ) => {
    setReport(null);
    setSelection({ period: periodKey, dimension, key: value.id });
  };

  const select = (key: string) => {
    setReport(null);
    setSelection({ period: periodKey, dimension: "accounting", key });
  };

  const accounting = totals.selected.flatMap((receipt) =>
    receipt.data!.lines.map((line) => ({
      receipt,
      line,
      amountOre: line.amountOre ?? 0,
    })),
  );

  const receiptContributions = (items: typeof receipts) =>
    items.map((receipt) => ({
      receipt,
      line: null,
      amountOre: receipt.data?.totalOre ?? 0,
    }));

  function moveMonth(offset: number) {
    const [year, value] = month.split("-").map(Number);
    setMonth(
      new Date(Date.UTC(year, value - 1 + offset, 1)).toISOString().slice(0, 7),
    );
    setGroup(null);
  }

  const meatRows = totals.categories.filter(
    (category) =>
      [
        "meat-fish.poultry",
        "meat-fish.pork",
        "meat-fish.lamb",
        "meat-fish.beef",
        "meat-fish.fish",
      ].includes(category.id) && category.amountOre !== 0,
  );

  const rawMonth = new Intl.DateTimeFormat("nb-NO", {
    month: "long",
    year: "numeric",
  }).format(new Date(`${month}-01T12:00:00Z`));

  const monthLabel =
    rawMonth.charAt(0).toLocaleUpperCase("nb-NO") + rawMonth.slice(1);

  const history = useCompleteReceipts(
    { kind: "allProducts" },
    report === "prices",
  );

  const surprises = history.completeReceipts
    ? monthPriceSignals(history.receipts, month)
    : [];

  const budgetOre = details?.household.monthlyBudgetOre ?? null;

  const pace =
    budgetOre && budgetOre > 0
      ? budgetPace(budgetOre, totals.products, month)
      : null;

  const selected = resolveSpendingSelection(selection, periodKey, {
    group: totals.groups,
    category: totals.categories,
    store: totals.stores,
    type: totals.purchaseTypes,
    catalogProduct: catalog.products,
    catalogBrand: catalog.brands,
    catalogStore: catalog.stores,
    attributeType: attributeInsights(totals.selected, "type").groups,
    attributeSugar: attributeInsights(totals.selected, "sugar").groups,
    attributePreparation: attributeInsights(totals.selected, "preparation")
      .groups,
    calendar: spendingCalendar(
      receipts,
      Number(month.slice(0, 4)),
      reviewedOnly,
    ).map((day) => ({
      id: day.date,
      name: day.date,
      amountOre: day.amountOre,
      contributions: day.contributions,
    })),
    change: comparison.changes.map((item) => ({
      id: item.id,
      name: item.name,
      amountOre: item.current,
      contributions: item.currentContributions,
    })),
    accounting: [
      {
        id: "paid",
        name: "Betalt",
        amountOre: totals.paid,
        contributions: receiptContributions(totals.selected),
      },
      {
        id: "Rabatter",
        name: "Rabatter",
        amountOre: totals.discounts,
        contributions: accounting.filter((item) =>
          ["item_discount", "receipt_discount"].includes(item.line.kind),
        ),
      },
      {
        id: "Pant betalt",
        name: "Pant betalt",
        amountOre: totals.deposits,
        contributions: accounting.filter(
          (item) => item.line.kind === "deposit",
        ),
      },
      {
        id: "Pant returnert",
        name: "Pant returnert",
        amountOre: totals.returns,
        contributions: accounting.filter(
          (item) => item.line.kind === "deposit_return",
        ),
      },
      {
        id: "previous",
        name: "Forrige periode",
        amountOre: comparison.previous.products,
        contributions: comparison.changes.flatMap(
          (item) => item.previousContributions,
        ),
      },
      {
        id: "unlinked",
        name: "Uten produktkobling",
        amountOre: 0,
        contributions: receiptContributions(coverage.unlinked),
      },
    ],
  });

  const reports = useSpendingReports({
    totals: { ...totals, undated: undated.receipts },
    coverageComplete: undated.completeReceipts,
    comparison,
    coverage,
    catalog,
    receipts,
    month,
    reviewedOnly,
    historyComplete: history.completeReceipts,
    surprises,
    meatRows,
    onSelect: showDetails,
    onAccounting: select,
    onClose: () => setReport(null),
  });

  return (
    <Screen
      summary={
        !loadingReceipts && (
          <Panel
            tone="primary"
            style={{
              padding: 20,
              paddingTop: 0,
              gap: 8,
              borderRadius: 0,
            }}
          >
            <View style={{ flexDirection: "row", alignItems: "center" }}>
              <Copy
                size={22}
                weight="600"
                style={{ color: colors.onHero, flex: 1 }}
              >
                {monthLabel}
              </Copy>
              <IconButton
                name="chevron.left"
                label="Forrige måned"
                size={16}
                color={colors.onHero}
                onPress={() => moveMonth(-1)}
              />
              <IconButton
                name="chevron.right"
                label="Neste måned"
                size={16}
                color={colors.onHero}
                disabled={month >= currentMonth}
                onPress={() => moveMonth(1)}
              />
            </View>
            <View
              style={{ flexDirection: "row", alignItems: "center", gap: 12 }}
            >
              <View style={{ flex: 1, gap: 8 }}>
                <Copy
                  size={12}
                  weight="600"
                  style={{ color: colors.onHeroMuted }}
                >
                  DAGLIGVARER
                </Copy>
                <Copy
                  size={36}
                  weight="600"
                  selectable
                  style={{ color: colors.onHero }}
                >
                  {formatMoney(totals.products)}
                </Copy>
                <Copy size={13} style={{ color: colors.onHeroMuted }}>
                  {totals.selected.length}{" "}
                  {totals.selected.length === 1 ? "kvittering" : "kvitteringer"}
                  {totals.provisional
                    ? ` · ${totals.provisional} foreløpige`
                    : ""}
                  {reviewedOnly ? " · bare godkjente" : ""}
                  {change !== null
                    ? ` · ${Math.abs(change)} % ${change > 0 ? "mer" : "mindre"} enn ${comparison.partial ? "samme del av forrige måned" : "forrige måned"}`
                    : ""}
                </Copy>
              </View>
              <MonumentArtwork scene="inbox" compact />
            </View>
            {pace && (
              <View style={{ gap: 6, paddingTop: 6 }}>
                <View
                  style={{
                    height: 6,
                    borderRadius: 3,
                    backgroundColor: "#FFFFFF33",
                    overflow: "hidden",
                  }}
                >
                  <View
                    style={{
                      height: 6,
                      borderRadius: 3,
                      width: `${Math.min(100, pace.spentShare * 100)}%`,
                      backgroundColor:
                        pace.status === "over" ? "#FFE3A1" : colors.onHero,
                    }}
                  />
                  {pace.elapsedShare > 0 && pace.elapsedShare < 1 && (
                    <View
                      style={{
                        position: "absolute",
                        left: `${pace.elapsedShare * 100}%`,
                        top: -2,
                        width: 2,
                        height: 10,
                        backgroundColor: "#FFFFFFAA",
                      }}
                    />
                  )}
                </View>
                <Copy
                  size={13}
                  weight="600"
                  style={{ color: colors.onHero, opacity: 0.9 }}
                >
                  {paceLabel(pace)}
                </Copy>
              </View>
            )}
          </Panel>
        )
      }
      title="Forbruk"
      settings
      headerRight={
        <IconButton
          name="line.3.horizontal.decrease"
          label="Filtrer forbruk"
          filled="#FFFFFF22"
          color={colors.onHero}
          size={17}
          onPress={() => setFilters(true)}
        />
      }
    >
      {!online && <Notice icon="wifi.slash">Uten nett</Notice>}
      {loadingReceipts ? (
        <Loading />
      ) : (
        <>
          {!completeReceipts && <Notice>Henter kvitteringer …</Notice>}
          {coverage.pending.length > 0 && (
            <Pressable
              accessibilityRole="button"
              onPress={() => router.navigate("/inbox")}
              style={(state) => [
                {
                  flexDirection: "row",
                  alignItems: "center",
                  gap: 12,
                  padding: 12,
                  paddingLeft: 14,
                  borderRadius: 14,
                  borderCurve: "continuous",
                  backgroundColor: colors.primarySoft,
                },
                pressed(state),
              ]}
            >
              <Icon name="tray.full" size={18} />
              <View style={{ flex: 1, gap: 1 }}>
                <Copy size={14} weight="600">
                  {coverage.pending.length === 1
                    ? "Én kvittering venter på kontroll"
                    : `${coverage.pending.length} kvitteringer venter på kontroll`}
                </Copy>
                <Copy size={12} muted numberOfLines={1}>
                  {receiptNeeds(coverage.pending[0]).slice(0, 2).join(" · ") ||
                    "Summene er foreløpige."}
                </Copy>
              </View>
              <Icon name="chevron.right" size={12} color={colors.secondary} />
            </Pressable>
          )}
          <View style={{ gap: 4 }}>
            <SectionTitle title="Fordeling" />
            <Segments
              value={breakdown}
              onChange={(value) => {
                setBreakdown(value);
                setGroup(null);
                setShowAllGroups(false);
              }}
              options={[
                { value: "category", label: "Kategori" },
                { value: "store", label: "Butikk" },
                { value: "type", label: "Varetype" },
              ]}
            />
            {group && (
              <Pressable
                accessibilityRole="button"
                onPress={() => setGroup(null)}
                style={(state) => [
                  {
                    flexDirection: "row",
                    alignItems: "center",
                    gap: 6,
                    minHeight: 36,
                  },
                  pressed(state),
                ]}
              >
                <Icon name="chevron.left" size={12} />
                <Copy size={14} weight="600" style={{ color: colors.primary }}>
                  Alle kategorier
                </Copy>
                <Copy size={14} muted>
                  · {categoryById.get(rows[0]?.id)?.groupName}
                </Copy>
              </Pressable>
            )}
            <SpendingBars
              rows={showAllGroups ? rows : rows.slice(0, 5)}
              total={totals.products}
              onSelect={(row) => {
                if (breakdown === "category" && !group) {
                  setGroup(row.id);
                  setShowAllGroups(false);
                } else
                  showDetails(
                    row,
                    breakdown === "store"
                      ? "store"
                      : breakdown === "type"
                        ? "type"
                        : group
                          ? "category"
                          : "group",
                  );
              }}
            />
            {rows.length > 5 && (
              <Row
                title={showAllGroups ? "Vis færre" : `Vis alle ${rows.length}`}
                onPress={() => setShowAllGroups(!showAllGroups)}
              />
            )}
            {!rows.length && (
              <Empty title="Ingen kjøp denne måneden" icon="cart" />
            )}
          </View>
          <Panel>
            <Row
              title="Butikker"
              detail="Se hvor dere handler, og hva dere bruker per butikk"
              icon="map"
              onPress={() => setStoresOpen(true)}
            />
          </Panel>
          <SectionTitle title="Betaling" />
          <Panel style={{ gap: 0, paddingVertical: 4 }}>
            <Row
              title="Betalt"
              detail="Inkludert pant"
              value={formatMoney(totals.paid)}
              onPress={() => select("paid")}
            />
            {[
              {
                name: "Rabatter",
                amount: totals.discounts,
                kinds: ["item_discount", "receipt_discount"],
              },
              {
                name: "Pant betalt",
                amount: totals.deposits,
                kinds: ["deposit"],
              },
              {
                name: "Pant returnert",
                amount: totals.returns,
                kinds: ["deposit_return"],
              },
            ].map((metric) => (
              <View
                key={metric.name}
                style={{ borderTopWidth: 1, borderTopColor: colors.line }}
              >
                <Row
                  title={metric.name}
                  value={formatMoney(metric.amount)}
                  onPress={() => select(metric.name)}
                />
              </View>
            ))}
          </Panel>
          <SectionTitle title="Utforsk forbruket" />
          <Row
            title="Forbruksanalyse"
            detail="Hva endret seg denne uken eller måneden?"
            icon="chart.bar"
            onPress={() =>
              router.push({ pathname: "/analysis", params: { month } })
            }
          />
          <Panel style={{ gap: 0, paddingVertical: 4 }}>
            {reportIds
              .filter((id) => reports[id].visible !== false)
              .map((id, index) => (
                <View
                  key={id}
                  style={{
                    borderTopWidth: index ? 1 : 0,
                    borderTopColor: colors.line,
                    paddingVertical: 2,
                  }}
                >
                  <Row
                    title={reports[id].title}
                    icon={reports[id].icon}
                    value={reports[id].value}
                    onPress={() => setReport(id)}
                  />
                </View>
              ))}
          </Panel>
        </>
      )}
      <StoreSpendingSheet
        visible={storesOpen}
        onClose={() => setStoresOpen(false)}
        purchases={totals.storePurchases}
        periodKey={periodKey}
        monthLabel={monthLabel}
        onPreviousMonth={() => moveMonth(-1)}
        onNextMonth={() => moveMonth(1)}
        nextDisabled={month >= currentMonth}
        loading={loadingReceipts}
      />
      <Sheet
        title={report ? reports[report].title : ""}
        visible={report !== null}
        onClose={() => setReport(null)}
      >
        {report ? reports[report].render() : null}
      </Sheet>
      <Sheet
        title="Vis forbruk"
        visible={filters}
        onClose={() => setFilters(false)}
      >
        <Panel>
          <Toggle
            label="Bare godkjente kvitteringer"
            value={reviewedOnly}
            onChange={setReviewedOnly}
          />
        </Panel>
        <Button title="Vis oversikt" onPress={() => setFilters(false)} />
      </Sheet>
      <SpendingDetails selected={selected} onClose={() => setSelection(null)} />
    </Screen>
  );
}
