// src/components/receipt-card.tsx
import { router } from "expo-router";
import { Pressable, View } from "react-native";
import { Copy, Icon } from "./ui";
import { useTheme } from "@/constants/theme";
import { formatDate } from "@/lib/format-date";
import { lineReviewIssues } from "@/lib/domain/receipt-review";
import type { Receipt } from "@/lib/domain/insights";
import { formatMoney } from "@/lib/domain/receipt";
export const statusLabels: Record<Receipt["status"], string> = {
  uploading: "Laster opp",
  uploaded: "Venter på behandling",
  processing: "Leser kvitteringen",
  needs_review: "Til kontroll",
  reviewed: "Kontrollert",
  failed: "Behandling mislyktes",
};
export function receiptStatusLabel(receipt: Receipt) {
  if (receipt.excluded) return "Utelatt";
  return receipt.status === "reviewed" && receipt.autoAccepted
    ? "Automatisk godkjent"
    : statusLabels[receipt.status];
}
export function openReceipt(receipt: Receipt) {
  router.push({ pathname: "/receipt/[id]", params: { id: receipt._id } });
}
export function ReceiptCard({ receipt }: { receipt: Receipt }) {
  const colors = useTheme();
  const uncertain =
    receipt.data?.lines.filter((line) => lineReviewIssues(line).length)
      .length ?? 0;
  return (
    <Pressable
      accessibilityRole="button"
      onPress={() => openReceipt(receipt)}
      style={({ pressed }) => ({
        backgroundColor: colors.surface,
        borderRadius: 14,
        padding: 14,
        gap: 6,
        opacity: pressed ? 0.65 : 1,
      })}
    >
      <View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}>
        <View style={{ flex: 1, gap: 3 }}>
          <Copy weight="600">{receipt.data?.store || "Ny kvittering"}</Copy>
          <Copy size={13} muted>
            {formatDate(receipt.data?.purchaseDate)}
            {receipt.data?.branch ? ` · ${receipt.data.branch}` : ""}
          </Copy>
        </View>
        {receipt.data && (
          <Copy weight="600">{formatMoney(receipt.data.totalOre)}</Copy>
        )}
        <Icon name="chevron.right" size={12} />
      </View>
      <Copy
        size={12}
        style={{
          color:
            receipt.status === "needs_review"
              ? colors.warning
              : colors.secondary,
        }}
      >
        {receiptStatusLabel(receipt)}
        {uncertain > 0
          ? ` · ${uncertain} ${uncertain === 1 ? "vare" : "varer"} må sjekkes`
          : ""}
        {receipt.duplicateOf && !receipt.duplicateResolved
          ? " · Mulig duplikat"
          : ""}
      </Copy>
      {!!receipt.error && (
        <Copy size={12} style={{ color: colors.danger }}>
          {receipt.error}
        </Copy>
      )}
    </Pressable>
  );
}

// src/lib/components/ReceiptCard.svelte
<script lang="ts">
	import { Button } from '#lib/components/ui/button/index.js';
	import { ChevronRight, ReceiptText, TriangleAlert, LoaderCircle, Check } from '@lucide/svelte';
	import type { Receipt } from '#lib/domain/insights.js';
	import { formatMoney } from '#lib/domain/receipt.js';
	let { receipt, onopen }: { receipt: Receipt; onopen: (receipt: Receipt) => void } = $props();
	const labels = {
		uploading: 'Laster opp',
		uploaded: 'Lastet opp',
		processing: 'Behandler',
		needs_review: 'Til kontroll',
		reviewed: 'Kontrollert',
		failed: 'Behandling feilet'
	};
	const active = $derived(['uploading', 'uploaded', 'processing'].includes(receipt.status));
	const date = $derived(
		receipt.data?.purchaseDate
			? new Intl.DateTimeFormat('nb-NO', {
					day: 'numeric',
					month: 'short',
					timeZone: 'Europe/Oslo'
				}).format(new Date(receipt.data.purchaseDate + 'T12:00:00Z'))
			: 'Dato ukjent'
	);
</script>

<Button variant="ghost" class="receipt-card" onclick={() => onopen(receipt)}>
	<span class="store-icon"><ReceiptText size={23} /></span>
	<span class="receipt-description"
		><strong>{receipt.data?.store ?? 'Ny kvittering'}</strong><span class="muted small"
			>{date} · {receipt.data?.lines.filter((l) => l.kind === 'product').length ?? '–'} varer</span
		><span class:warning={receipt.status === 'failed' || !!receipt.duplicateOf} class="status-label"
			>{#if active}<LoaderCircle
					size={12}
					class="spin"
				/>{:else if receipt.status === 'reviewed'}<Check
					size={12}
				/>{:else if receipt.status === 'failed' || receipt.duplicateOf}<TriangleAlert
					size={12}
				/>{/if}{receipt.excluded
				? 'Utelatt fra forbruk'
				: receipt.duplicateOf && !receipt.duplicateResolved
					? 'Mulig duplikat'
					: receipt.autoAccepted
						? 'Automatisk godkjent'
						: labels[receipt.status]}</span
		></span
	>
	<span class="receipt-price"
		>{formatMoney(receipt.data?.totalOre ?? null)}<ChevronRight size={16} /></span
	>
</Button>
